# Generated by Django 6.1.1 on 2026-09-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('web_name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fixtures.team')),
            ],
        ),
    ]
