# Generated by Django 6.1.1 on 2026-09-05 17:45

import backend.leagues.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[backend.leagues.validators.validate_no_profanity])),
                ('public_id', models.CharField(editable=False, max_length=8, unique=True)),
                ('code', models.CharField(editable=False, max_length=6, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public leagues are listed for anyone to browse and join freely.')),
                ('max_members', models.PositiveSmallIntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64'), (128, '128')], default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='leagues', through='leagues.LeagueMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
