# Generated by Django 6.1.1 on 2026-09-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public leagues are listed for anyone to browse and join freely.'),
        ),
    ]
