# Generated by Django 6.1.1 on 2026-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_league_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='starting_gameweek',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
